#!/bin/sh /etc/rc.common
START=99

restart(){                                                                                                       
	# sendat 1 "AT+CFUN=1,1"
  modem_init
	#/usr/share/modem/rm520n.sh &
}

start(){
  modem_init
	#/usr/share/modem/rm520n.sh &
   
}

printMsg() {
    local msg="$1"
    logger -t "${PROGRAM}" "${msg}"
} #日志输出调用API



ModuleCheck(){
  local count=0
  while [ $count -lt 10 ]; do
    echo 1 >/sys/class/gpio/cpe-pwr/value
    echo "USB串口1模式已连接" >>/tmp/stsss_u.file
    Readmodule=$(sendat 2 'ATI' | sed -n '3p')
    if echo "$Readmodule" | grep -q 'RM520' || echo "$Readmodule" | grep -q 'RM500' ; then
        echo "The module is working properly"
        check_and_update_simsel
        return 0
    fi

    #Read the Balong module
    Read_mt5700_USB=$(lsusb | grep 'MT5700M' |grep -v grep)
    if ! [ "$Read_mt5700_USB" == "" ] ; then
      Readmodule=$(sendat 1 'ATI' | sed -n '3p')
      if echo "$Readmodule" | grep -q 'MT5700' ; then
          echo "The module is working properly"
          check_and_update_simsel_mt5700
          return 0
      fi    
    fi

    sleep 3
    count=$((count + 1)) 
  done
  echo "Failed to confirm the module status after 10 attempts."
  return 1
}

modem_init(){

  ipcheckLOCKFILE="/tmp/ipcheck.lock"
  if [ -f /usr/bin/ledflagc.conf ]; then
      echo "0" > /tmp/ledflag.conf
      echo 0 > /sys/class/leds/hc:blue:cmode4/brightness
      echo 0 > /sys/class/leds/hc:blue:cmode5/brightness
      echo 0 > /sys/class/leds/hc:blue:wifi/brightness
      echo 0 > /sys/class/leds/hc:blue:status/brightness
      echo 0 > /sys/class/leds/hc:blue:sig1/brightness
      echo 0 > /sys/class/leds/hc:blue:sig2/brightness
      echo 0 > /sys/class/leds/hc:blue:sig3/brightness
      echo 0 > /sys/class/leds/hc:blue:int/brightness
  else
      echo 1 > /sys/class/leds/hc:blue:wifi/brightness
  fi
  # Check if lockfile exists
  if [ -f $ipcheckLOCKFILE ]; then
      OLD_PID=$(cat $ipcheckLOCKFILE)
      echo "$(date): Kill $OLD_PID" 
      kill $OLD_PID
  fi
    lock_file="/tmp/moduleInit.lock"

    if [ -e "$lock_file" ]; then
    # 锁文件存在，获取锁定的进程 ID，并终止它
    locked_pid=$(cat "$lock_file")
        if [ -n "$locked_pid" ]; then
            echo "Terminating existing moduleInit process (PID: $locked_pid)..." >>/tmp/moduleInit
            kill "$locked_pid"
            sleep 2  # 等待一段时间确保进程终止
        fi
    fi
     
      Modem_Enable=`uci -q get modem.@ndis[0].enable` || Modem_Enable=1
      # 模块启动
      # 模块开关
      if [ "$Modem_Enable" == 0 ]; then
          echo 0 >/sys/class/gpio/cpe-pwr/value
          printMsg "禁用模块，退出"
          rm $lock_file
          exit 0
      else
          #加载MT5700（模组）端口
          echo "3466 3301" > /sys/bus/usb-serial/drivers/generic/new_id
          sleep 1
          printMsg "模块启用"
          # 检测模块是否开机了！
          ModuleCheck
          sleep 1
          /usr/bin/BLUE4WAN.sh
          # 判断第三行文本并执行相应操作
          third_line=$(sendat 2 'ATI' | sed -n '3p')
          third_line2=$(sendat 1 'ATI' | grep 'Model' | sed -n '1p')
          if [ -n "$third_line" ]; then
              if echo "$third_line" | grep -q 'RM520'; then
                  echo "$third_line" > /tmp/modconf.conf
                  echo "set" > "/tmp/CPEstartupSettings"
                  sendat 2  'AT+QMAP="connect",0,0'
                  sleep 1
                  /usr/share/modem/rm520n.sh &
                  sleep 1
                  /usr/share/modem/netmodeled.sh &
              elif echo "$third_line" | grep -q 'RM500'; then
                  echo "$third_line" > /tmp/modconf.conf
                  /usr/share/modem/500U.sh &
                  /usr/share/modem/netmodeled.sh &
              fi
          elif [ -n "$third_line2" ]; then
              if echo "$third_line2" | grep -q 'MT5700'; then
                echo "$third_line2" > /tmp/modconf.conf
                echo "set" > "/tmp/CPEstartupSettings"
                /usr/share/modem/mt5700m.sh &
                /usr/share/modem/netmodeled.sh &
              fi
          else
              echo "未检测到模组" > /tmp/modconf.conf
              echo "第三行文本为空或不包含指定内容"
          fi
          echo "已尝试开启短信转发服务。"
          python3 /usr/bin/smstrun.py &
          python3 /usr/bin/httpapi.py &
      fi
}

check_and_update_simsel() {
  local sim_slot=$(sendat 2 "AT+QUIMSLOT?" | grep '+QUIMSLOT:' | awk '{print $2}')
  local sim_sel_file="/etc/simsel"

  # 如果 sim_sel_file 不存在，则创建并写入外置卡 SIM 卡槽值，仅用于修正刷机和ui显示问题
  if [ ! -e "$sim_sel_file" ]; then
    echo 1 > "$sim_sel_file"
    sendat 2 "AT+QUIMSLOT=1"
  fi
}
check_and_update_simsel_mt5700() {
  local sim_sel_file="/etc/simsel"
  if [ ! -e "$sim_sel_file" ]; then
    echo 1 > "$sim_sel_file"
    sendat 1 "AT^SCICHG=0,1"
  fi
}






